FROM node:10
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm install
ADD . /app
ENV NODE_ENV production
ARG IS_TESTNET
ENV IS_TESTNET ${IS_TESTNET}
ARG RELEASE
ENV RELEASE ${RELEASE}
ARG GTM_ID
ENV GTM_ID ${GTM_ID}
ARG SENTRY_PROJECT
ENV SENTRY_PROJECT ${SENTRY_PROJECT}
ARG SENTRY_DSN
ENV SENTRY_DSN ${SENTRY_DSN}
ARG SENTRY_AUTH_TOKEN
ENV SENTRY_AUTH_TOKEN ${SENTRY_AUTH_TOKEN}
ARG SENTRY_REPORT_URI
ENV SENTRY_REPORT_URI ${SENTRY_REPORT_URI}
RUN npm run build
ENV HOST 0.0.0.0
EXPOSE 3000
USER 1337
CMD npm start
